### ISSUE TITLE
possible problem with double qouted data after a named placeholder

### ISSUE THREAD

**Issue by danieljuhl** [sidorares/named-placeholders#2] opened 2015-11-12 10:31 UTC
I've tried to create the most minimal case, where this happens (used with `node-mysql2`):

`conn.execute('SELECT * FROM items WHERE id = :id AND deleted = "0000-00-00 00:00:00";', { id: Number(id) })` fails, but `conn.execute('SELECT * FROM items WHERE deleted = "0000-00-00 00:00:00" AND id = :id;', { id: Number(id) })` works fine.

For some reason the first one is converted to: `SELECT * FROM items WHERE id = ?";`

**Comment by sidorares** [comment] 2015-11-12 10:46
what's the result of resolving named placeholders? can you print `unnamed` at https://github.com/sidorares/node-mysql2/blob/master/lib/connection.js#L405 ?

**Comment by sidorares** [comment] 2015-11-12 10:51
looks like a bug in named_placeholders compiler ( might be caused by "0000-00-00 00:00:00" )

**Comment by sidorares** [comment] 2015-11-12 10:57
it's ok if I delete ":" from date, so probably bug in parser in "in quote" state. Might be also the case for @mscdex node-mariasql

**Comment by danieljuhl** [comment] 2015-11-12 11:42
Seems very likely...

**Comment by danieljuhl** [comment] 2015-11-12 11:42
@sidorares  you still want unnamed?

**Comment by sidorares** [comment] 2015-11-12 11:57
no, no need, run it locally myself

**Comment by danieljuhl** [comment] 2015-11-12 13:14
Perfect - let me know, if there is anything I can do.

**Comment by sidorares** [comment] 2015-11-12 13:28
it's definitely a bug, I'll try to fix it

**Closed** 2015-11-25 04:46 UTC
